// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wirehome.Core.History.Repository.Entities;

namespace Wirehome.Core.Migrations
{
    [DbContext(typeof(HistoryDatabaseContext))]
    partial class HistoryDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Wirehome.Core.History.Repository.Entities.ComponentStatusEntity", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComponentUid")
                        .HasMaxLength(256);

                    b.Property<uint?>("NextEntityID");

                    b.Property<uint?>("PreviousEntityID");

                    b.Property<DateTime>("RangeEnd");

                    b.Property<DateTime>("RangeStart");

                    b.Property<string>("StatusUid")
                        .HasMaxLength(256);

                    b.Property<string>("Value")
                        .HasMaxLength(1024);

                    b.HasKey("ID");

                    b.HasIndex("NextEntityID")
                        .IsUnique();

                    b.HasIndex("PreviousEntityID");

                    b.HasIndex("RangeStart", "RangeEnd", "ComponentUid", "StatusUid");

                    b.ToTable("ComponentStatus");
                });

            modelBuilder.Entity("Wirehome.Core.History.Repository.Entities.ComponentStatusEntity", b =>
                {
                    b.HasOne("Wirehome.Core.History.Repository.Entities.ComponentStatusEntity", "NextEntity")
                        .WithOne()
                        .HasForeignKey("Wirehome.Core.History.Repository.Entities.ComponentStatusEntity", "NextEntityID");

                    b.HasOne("Wirehome.Core.History.Repository.Entities.ComponentStatusEntity", "PreviousEntity")
                        .WithMany()
                        .HasForeignKey("PreviousEntityID");
                });
#pragma warning restore 612, 618
        }
    }
}
